### ISSUE TITLE
Source stops at some point while building

### ISSUE THREAD

**Issue by DeletedArch** [Evolution-X/packages_apps_Evolution#157]
Building on Cirrus CI and got this issue
source was working fine yesterday and building perfectly
![Screenshot_20210325-123540_Brave](https://user-images.githubusercontent.com/35235801/112470194-0afc6280-8d73-11eb-9234-87e9eb36ea28.png)
it's always at 11%

**Comment by joeyhuab** [comment]
Fixed.
