### ISSUE TITLE
Trying to completely undo the custom volume step modifications

### ISSUE THREAD

**Issue by derivativeoflog7** [Evolution-X/packages_apps_Evolution#318]
Hello, I apologize if this is not the place to ask this, but I'm having trouble with the custom volume step settings.

Basically, after enabling them, I discovered that touching these settings breaks Viper4Android as toggling settings in in seems to no longer have any effect, and to an extent it also breaks YouTube ReVanced (the volume slider normally allows you to finely tune the volume from 0 to 100, or actually to 150 if you have V4A's volume boost enabled, but after messing with the settings it only goes from 0 to whatever you set the volume steps to)

Even if you use the built in settings to reset the values, it doesn't work, because it seems to just set the steps to the predefined value but does not undo everything (so I still only get 15 steps with YTRV and V4A still doesn't work)

After taking a look at the source code, I tried editing the settings database to remove all the volume_steps_* settings, but even after restarting it still doesn't revert to the normal state

What am I missing?

(yes I could simply do a wipe, but I'll leave that as a last last resort)

**Comment by joeyhuab** [comment]
No idea how to even debug this in the first place as both V4A and ReVanced are out of the ROM's handling since they are both Magisk modules, and without any proper logs, there's no telling what went wrong with your setup.

Closing until proper evidence arrives.

**Comment by derivativeoflog7** [comment]
I know touching the volume levels settings is what causes the issues, both because I've replicated it multiple times on my phone, and because I had the same issues when messing with the volume levels on other ROMs. All I need is to figure out what else I'm missing to restore everything to a state where it's like I've never touched these settings before
