### ISSUE TITLE
Crash UDFPS Settings

### ISSUE THREAD

**Issue by weritos666** [Evolution-X/packages_apps_Evolution#443]
05-01 16:35:18.366  7534  7534 E AndroidRuntime: FATAL EXCEPTION: main
05-01 16:35:18.366  7534  7534 E AndroidRuntime: Process: com.android.settings, PID: 7534
05-01 16:35:18.366  7534  7534 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.setOnPreferenceChangeListener(androidx.preference.Preference$OnPreferenceChangeListener)' on a null object reference
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3642)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3779)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7926)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.setOnPreferenceChangeListener(androidx.preference.Preference$OnPreferenceChangeListener)' on a null object reference
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at com.evolution.settings.fragments.Udfps.onCreate(Udfps.java:114)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3009)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1780)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:586)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:776)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:558)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at com.android.settings.SettingsActivity.createUiFromIntent(SettingsActivity.java:310)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:269)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8347)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8326)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1424)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
05-01 16:35:18.366  7534  7534 E AndroidRuntime: 	... 12 more
05-01 16:35:18.368  1326  1509 W ActivityTaskManager:   Force finishing activity com.android.settings/.SubSettings
05-01 16:35:18.374  1326  1509 W ActivityTaskManager:   Force finishing activity com.android.settings/.SubSettings
05-01 16:35:18.375  1326  1593 I ActivityManager: Showing crash dialog for package com.android.settings u0
05-01 16:35:18.394  1326  1593 D CoreBackPreview: Window{365a0b7 u0 Application Error: com.android.settings}: Setting back callback

**Comment by joeyhuab** [comment]
https://github.com/Evolution-X/packages_apps_Evolver/commit/42c4843e9265478e995e5d2f183a4bd5a4a9d557

Should be fixed with that ^. Lemme know if it still crashes.
