### ISSUE TITLE
Error setting FOD / UDFPS icon on Mi 11 (Venus)

### ISSUE THREAD

**Issue by alryaz** [Evolution-X/packages_apps_Evolution#457]
Hello!

I've encountered an issue when after selecting a custom FOD icon through a file picker it just doesn't show up on my lock screen (the area is blank; there's not even a default icon). I am using a PNG file with transparency.

I will provide additional information if necessary, however I'm using the very latest update.

**Comment by alryaz** [comment]
Next message right after opening a .WebP image:
`05-23 07:20:50.165 D/SettingsActivity(21188): No enabled state changed, skipping updateCategory call`

**Comment by joeyhuab** [comment]
> Hello!
> 
> I've encountered an issue when after selecting a custom FOD icon through a file picker it just doesn't show up on my lock screen (the area is blank; there's not even a default icon). I am using a PNG file with transparency.
> 
> I will provide additional information if necessary, however I'm using the very latest update.

Use QuickPic or different gallery apps than Google Photos.
