### ISSUE TITLE
Dual Apps Notification Bug

### ISSUE THREAD

**Issue by rafelis1997** [Evolution-X/packages_apps_Evolution#517]
## Context

There is a bug that barriers Gboard to open when trying to respond notifications like telegram when the app is from the dual spaces.

The bug is even worse when you try to respond when notification pops up in the screen causing a jittering to both the notification balloon and Gboard.

## Device

**Brand**: Mi 9t Pro
**Android Version**: 12
**Evolution-X Version**: 7.8.9 (Lugaw) | raphael | OFFICIAL
**Evolution-X Build**: evolution_raphael-userdebug 13 TQ3C.230901.001.B1.1696339292 release-keys

<img src="https://github.com/Evolution-X/packages_apps_Evolver/assets/60658855/74dab2f6-5b82-4c11-aaf1-7c7c0bf8d8aa" height="500px"/>

**Comment by joeyhuab** [comment]
We don't support outdated builds.
