### ISSUE TITLE
Wakelock blocker crash on save

### ISSUE THREAD

**Issue by cmeka** [Evolution-X/packages_apps_Evolution#607]
Wakelock blocker crashes each time I press the save button, error suggests the setting string is now too long.

Not sure this is fixable without changing the data type of the setting storage however an improvement would be to add a button to reset the blocklist and seen wakelocks which would at least allow me to start from scratch.

[wakelock-blocker-save-error.txt](https://github.com/Evolution-X/packages_apps_Evolver/files/14302799/wakelock-blocker-save-error.txt)

ROM: evolution_cheetah-ota-uq1a.240205.004-02080128-OFFICIAL

**Comment by joeyhuab** [comment]
Fixed via https://github.com/Evolution-X/frameworks_base/commit/4919d3d8a2d3dc29f2533a8231ec6186b95845be
