### ISSUE TITLE
Theming settings in The Evolver are hanging

### ISSUE THREAD

**Issue by QuinceROMs** [Evolution-X/packages_apps_Evolution#625]
Something is wrong with one of the commits from recent days. After entering the Theming settings, the screen freezes and jams, and when it turns off, the system goes to lockscreen and returning to the system from there is very difficult. I am compiling unofficially for OnePlus 7 based on the OxygenOS 11.0.9.1 firmware and the build from February 28 had no such symptoms, everything worked. I am attaching logs from Logcat Extreme.

[Log_2024-03-03_10-42-04.zip](https://github.com/Evolution-X/packages_apps_Evolver/files/14472479/Log_2024-03-03_10-42-04.zip)

**Comment by joeyhuab** [comment]
Check if still happening. Should be fixed

**Comment by QuinceROMs** [comment]
It's slightly better, I could now select the style and color source, but Theming settings started freezing when trying to set the accent background. For now, I have uploaded the build to my second (test) OnePlus 7; I'll flash my daily one soon and try to save the logs.

**Comment by QuinceROMs** [comment]
I think I found the culprit. The problems start when you try to select the Preset option in the Color source menu, The Evolver also restarts every now and then. Symptoms disappear when one of the other three is chosen.

[drive-download-20240303T223204Z-001.zip](https://github.com/Evolution-X/packages_apps_Evolver/files/14474849/drive-download-20240303T223204Z-001.zip)

**Comment by joeyhuab** [comment]
> I think I found the culprit. The problems start when you try to select the Preset option in the Color source menu, The Evolver also restarts every now and then. Symptoms disappear when one of the other three is chosen.
> 
> [drive-download-20240303T223204Z-001.zip](https://github.com/Evolution-X/packages_apps_Evolver/files/14474849/drive-download-20240303T223204Z-001.zip)

Thanks, I'll check further!

**Comment by joeyhuab** [comment]
> I think I found the culprit. The problems start when you try to select the Preset option in the Color source menu, The Evolver also restarts every now and then. Symptoms disappear when one of the other three is chosen.
> 
> [drive-download-20240303T223204Z-001.zip](https://github.com/Evolution-X/packages_apps_Evolver/files/14474849/drive-download-20240303T223204Z-001.zip)

I've fully disabled the Monet settings. Should fully resolved this. Thanks.

**Comment by QuinceROMs** [comment]
Agreed. Thank you.
